In [2]:
import numpy as np

# Define functions for OLSLR and regularized OLSLR
def direct_ols_gradient(A, x, y):
    return A.T @ (A @ x - y)

def direct_ols_hessian(A):
    return A.T @ A

def regularized_ols_gradient(A, x, y, lam):
    return A.T @ (A @ x - y) + lam * x

def regularized_ols_hessian(A, lam):
    return A.T @ A + lam * np.eye(A.shape[1])

# Newton's method
def newton_method(A, y, x0, tol, lam=None, max_iter=100):
    x = x0
    iterations = 0
    history = []

    for _ in range(max_iter):
        if lam is None:
            grad = direct_ols_gradient(A, x, y)
            hessian = direct_ols_hessian(A)
        else:
            grad = regularized_ols_gradient(A, x, y, lam)
            hessian = regularized_ols_hessian(A, lam)

        # Check for invertibility of Hessian
        if np.linalg.cond(hessian) > 1e12:  # Condition number threshold
            raise ValueError("Hessian is ill-conditioned, Newton's method cannot proceed.")

        # Update x using Newton's method
        delta_x = np.linalg.solve(hessian, -grad)
        x += delta_x
        history.append((x.copy(), np.linalg.norm(grad)))

        # Convergence check
        if np.linalg.norm(grad) < tol:
            break

        iterations += 1

    return x, iterations, history


# Generate data
np.random.seed(42)
m, n = 100, 10
A = np.random.randn(m, n)
x_true = np.random.randn(n, 1)
y = A @ x_true + 0.1 * np.random.randn(m, 1)

# Initial values and parameters
x0 = np.zeros((n, 1))
tol = 1e-6
lambda_val = 0.001

# Solve direct OLSLR
try:
    x_star_f, iters_f, history_f = newton_method(A, y, x0, tol)
    print("Direct OLSLR converged.")
    print(f"x_star_f:\n{x_star_f}")
    print(f"Iterations: {iters_f}")
except ValueError as e:
    print("Direct OLSLR encountered difficulties:", e)

# Solve regularized OLSLR
try:
    x_star_f_lambda, iters_f_lambda, history_f_lambda = newton_method(A, y, x0, tol, lam=lambda_val)
    print("\nRegularized OLSLR converged.")
    print(f"x_star_f_lambda:\n{x_star_f_lambda}")
    print(f"Iterations: {iters_f_lambda}")
except ValueError as e:
    print("Regularized OLSLR encountered difficulties:", e)

Direct OLSLR converged.
x_star_f:
[[ 1.39881378]
 [ 0.92272046]
 [ 0.05350896]
 [-0.6436528 ]
 [ 0.70291004]
 [ 0.38370306]
 [ 0.89052904]
 [ 0.65774029]
 [ 1.07197851]
 [-0.53316061]]
Iterations: 1

Regularized OLSLR converged.
x_star_f_lambda:
[[ 1.39879722]
 [ 0.92270548]
 [ 0.05350939]
 [-0.6436425 ]
 [ 0.70290481]
 [ 0.38369709]
 [ 0.89051358]
 [ 0.65773517]
 [ 1.07196301]
 [-0.53316159]]
Iterations: 1


In [1]:
import numpy as np
from sklearn.datasets import load_digits
from numpy.linalg import norm

# Load the digits dataset and prepare A and y
digits = load_digits()
A = digits.data
y = digits.target.reshape(-1, 1)

# Newton's Method Implementation
def newton_method_direct_ols(A, y, tol=1e-6, max_iter=100):
    n = A.shape[1]
    x = np.zeros((n, 1))  # Starting point
    iter_count = 0

    while iter_count < max_iter:
        # Gradient
        grad = A.T @ (A @ x - y)

        # Hessian
        hess = A.T @ A

        # Check if Hessian is invertible
        if np.linalg.cond(hess) > 1e12:
            print("Hessian is ill-conditioned. Newton's method may fail.")
            break

        # Newton's update step
        delta_x = np.linalg.solve(hess, -grad)
        x += delta_x

        # Convergence check
        if norm(grad) < tol:
            break

        iter_count += 1

    return x, iter_count

# Solve Direct OLSLR
print("Solving Direct OLSLR...")
x_star_f, iterations_direct = newton_method_direct_ols(A, y)
print(f"x_star_f:\n{x_star_f}\nIterations: {iterations_direct}")

# Observations
print("\nObservations:")
print("Direct OLSLR might encounter issues with ill-conditioned matrices if A.T @ A is singular or near-singular.")

Solving Direct OLSLR...
Hessian is ill-conditioned. Newton's method may fail.
x_star_f:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Iterations: 0

Observations:
Direct OLSLR might encounter issues with ill-conditioned matrices if A.T @ A is singular or near-singular.
